### ISSUE TITLE
Module 'UIKit' not found

### ISSUE THREAD

**Issue by aalenliang** [madebybowtie/FlagKit#41]
I'm using FlagKit for macOS project, programming in Swift 3.
My system is OS X 10.11.6, platform is Xcode 8, Carthage 0.18.
In my Cartfile, I wrote:
github "madebybowtie/FlagKit" "swift3"

After I drag the framework into my project and build after import flagkit, I got two errors said:
.../Carthage/Build/Mac/FlagKit.framework/Headers/FlagKit-Swift.h:113:9: Module 'UIKit' not found
MyClass.swift:12:8: Could not build Objective-C module 'FlagKit'

**Comment by TomLiu** [comment]
I think the problem is we can't build FlagKit for macOS using the existing config after the commit "99c1de75aa51bc2f77d857d947b66f8e54e508c5"

<img width="920" alt="2016-10-04 1 04 01" src="https://cloud.githubusercontent.com/assets/704820/19046145/b49507fa-89ce-11e6-9356-e623da60f040.png">

<img width="963" alt="2016-10-04 1 04 51" src="https://cloud.githubusercontent.com/assets/704820/19046212/e8d95930-89ce-11e6-8fc7-4ddc2fe897d2.png">

I think the baseSDK and Architecture are not fit for building macOS framework

**Comment by aalenliang** [comment]
#40 

As I mentioned in another issue, it looks like Carthage's issue.

Carthage seems to try to copy the file in 
"/Users/User/Library/Developer/Xcode/DerivedData/FlagKit-elyskaizpvzagzbknlniohvnpdaa/Build/Products/Release-iphoneos/FlagKit.framework"
to
".../MyProject/Carthage/Build/Mac/FlagKit.framework"

Therefore the framework under "Build/Mac/FlagKit.framework" is actually for iPhone OS, hence it include 'UIKit', which macOS failed to build. After building and copying the framework to my project manually, it works fine.

However I still don't understand why other frameworks works fine, I find 'SnapKit' has the same issue too, I will look into Carthage source code to find the reason.

**Comment by aalenliang** [comment]
I firmly believe it's carthage's issue, it tries to copy frameworks for projects base sdk to '/Build/Mac'.
I open a issue for carthage.
https://github.com/Carthage/Carthage/issues/1513

**Comment by ikesyo** [comment]
See https://github.com/Carthage/Carthage/issues/1513#issuecomment-251543160.
